name: Run Sudo Command on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Sudo Command on EC2
        run: |
          ssh -o StrictHostKeyChecking=no root@ec2-18-119-3-208.us-east-2.compute.amazonaws.com << 'EOF'
          sudo mkdir /opt/myfolder 
          EOF

            