name: Run Sudo Command on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Change to Blinkly directory
        run: |
          cd /opt/BlinklyRepo/Blinkly
          pwd  # Print working directory to verify location

      - name: Pull latest changes
        run: |
          cd /opt/Blinkly
          git pull

      - name: Stop wildduck service
        run: |
          sudo systemctl stop wildduck-webmail.service

            