name: Update Repo 2 on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Clean up workspace
        run: |
          sudo rm -rf /opt/actions-runner/_work/cicd/cicd/*  # Clean previous workspace

      - name: Checkout repo 2 (Blinkly)
        uses: actions/checkout@v2
        with:
          repository: blinkly-crypto/Blinkly  # Your repo 2
          token: ${{ secrets.BLINKLY_PAT }}  # Personal Access Token for authentication
          path: cicd/Blinkly  # Checkout path for the repository

      - name: List contents of the cicd directory
        run: |
          ls -la /opt/actions-runner/_work/cicd/cicd  # List contents to verify checkout

      - name: List contents of the Blinkly directory
        run: |
          ls -la /opt/actions-runner/_work/cicd/cicd/Blinkly  # Check if Blinkly directory exists

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Mark Blinkly directory as safe
        run: |
          sudo git config --global --add safe.directory /opt/actions-runner/_work/cicd/cicd/Blinkly

      - name: Change to Blinkly directory
        run: |
          cd /opt/actions-runner/_work/cicd/cicd/Blinkly || exit 1  # Navigate to Blinkly directory

      - name: Pull latest changes in repo 2
        run: |
          cd /opt/actions-runner/_work/cicd/cicd/Blinkly || exit 1
          sudo git pull origin main  # Pull the latest changes from the main branch

      - name: Stop wildduck service
        run: |
          sudo systemctl stop wildduck-webmail.service

      - name: Remove existing wildduck-webmail directory
        run: |
          sudo rm -rf /opt/wildduck-webmail

      - name: Create folder /opt/wildduck-webmail
        run: |
          sudo mkdir /opt/wildduck-webmail

      - name: Copy content to /opt/wildduck-webmail
        run: |
          sudo cp -rf /opt/actions-runner/_work/cicd/cicd/Blinkly/. /opt/wildduck-webmail  # Copy files to new directory

      - name: Change permissions for wildduck-webmail
        run: |
          sudo chmod -R 755 /opt/wildduck-webmail

      - name: Change ownership of wildduck-webmail
        run: |
          sudo chown -R deploy:deploy /opt/wildduck-webmail

      - name: Create .env file
        run: |
          sudo bash -c 'cat <<EOF > /opt/wildduck-webmail/.env
          DB_PROTOCOL=mongodb+srv
          DB_USER=testAdmin
          DB_PASS=uPhqo99tXHOc4Kc8
          DB_NAME=wildduck
          DB_URL=test-blinkly-com.uapme.mongodb.net
          STRIPE_KEY=sk_test_6xHWgDHD3TGEszepeyIvw3rR00Stfps2C6
          NOTIFICATION_USER=notification
          NOTIFICATION_PASSWORD=f186694a-f044-4753-92f9-6f99c98701df
          replyAllDefaultUser=via@test.blinkly.com
          replyAllDefaultPswd=bac4341a-3b32-4870-88fd-410e914acc08
          VC_API_URL=https://vc.blinkly.com
          VC_API_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGM2MzI5ZWI3OGNiOWE1MzQ3MDk2YyIsInVzZXJuYW1lIjoiYmxpbmtseWVtYWlsIiwiaWF0IjoxNzA3NDYyMjAzLCJleHAiOjE3Mzg5OTgyMDN9.MA0COixzWuPyOy1yITivMiuuUgBtENE-54ikGIqR1Pg
          CHAT_API_URL=https://test.blinkly.com/chatserver/api/v1
          EOF'

      - name: Run installation and build commands
        run: |
          cd /opt/wildduck-webmail
          sudo node -e "const { execSync } = require('child_process'); execSync('npm ci', { stdio: 'pipe', maxBuffer: 1024 * 1024 * 10 })" > npm_install.log 2>&1  # Log output to npm_install.log
          sudo npm run bowerdeps > npm_bowerdeps.log 2>&1

      - name: Updating files
        run: |
          sudo sed -i 's|domain="localhost"|domain="staging.blinkly.com"|g' /opt/wildduck-webmail/config/default.toml
          sudo sed -i 's|blinkly.com|staging.blinkly.com|g' /opt/wildduck-webmail/public/login-key-handler.js
          sudo sed -i 's|nonBlinklyEmail="nonblinkly@blinkly.com"|nonBlinklyEmail="staging.blinkly.com"|g' /opt/wildduck-webmail/config/default.toml
          sudo sed -i 's|Stripe("pk_live_.*")|Stripe("pk_test_L97sPGzIcJfHVwh5KVg8NQMv00a50cuGg0")|g' /opt/wildduck-webmail/public/new/js/client.js

      - name: Create Env file inside Blinkly-email-app
        run: |
          sudo bash -c 'cat <<EOF > /opt/wildduck-webmail/blinkly-email-app/.env
          REACT_APP_IO_URL=https://test.blinkly.com
          REACT_APP_SERVER_URL=https://test.blinkly.com/chatserver
          REACT_APP_CHAT_API_ENDPOINT=https://test.blinkly.com/chatserver
          REACT_APP_FILE_PATH=https://test.blinkly.com/chatserver/api/v1/files
          REACT_APP_TURN_URL=turn:18.119.3.208:3478
          REACT_APP_TURN_USERNAME=admin
          REACT_APP_TURN_PASSWORD=webkul123
          EOF'

      - name: Install packages in blinkly-email-app
        run: |
          cd /opt/wildduck-webmail/blinkly-email-app
          sudo node -e "const { execSync } = require('child_process'); execSync('npm ci', { stdio: 'pipe', maxBuffer: 1024 * 1024 * 10 })" > npm_install_blinkly_email.log 2>&1
          sudo npm run build > npm_build.log 2>&1  # Log output to npm_build.log

      - name: Restart wildduck service
        run: |
          sudo systemctl start wildduck-webmail.service
