name: Run Sudo Command on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: blinkly-crypto/Blinkly  # Your repository
          token: ${{ secrets.BLINKLY_PAT }}  # Your Personal Access Token for authentication

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Mark Blinkly directory as safe
        run: |
          git config --global --add safe.directory /opt/Blinkly

      - name: Change to Blinkly directory
        run: |
          cd /opt/Blinkly
          pwd  # Print working directory to verify location

      - name: Configure Git to use PAT for Pull
        run: |
          cd /opt/Blinkly
          git remote set-url origin https://imtiyaz.ahmad@ideavate.com:${{ secrets.GITHUB_PAT }}@github.com/blinkly-crypto/Blinkly.git

      - name: Pull latest changes
        run: |
          cd /opt/Blinkly
          sudo git pull

      - name: Stop wildduck service
        run: |
          sudo systemctl stop wildduck-webmail.service
